development:
  adapter: postgresql
  encoding: unicode
  database: clothes_consensus
  pool: 2
  username: localuser
  password: localpassword
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: your_username
  password: your_password